(() => {
  const supportCopy = {
    pt: {supportFormKicker:'SUPORTE BOLTMIND',supportFormTitle:'Envie sua dúvida ou sugestão',supportFormLead:'Preencha os dados abaixo. Sua mensagem será encaminhada diretamente ao atendimento.',supportName:'Seu nome',supportEmail:'Seu e-mail',supportTopic:'Assunto',supportTopicQuestion:'Dúvida',supportTopicSuggestion:'Sugestão',supportTopicPurchase:'Compra',supportMessage:'Dúvida ou sugestão',supportPlaceholder:'Escreva sua mensagem. Não envie senhas, códigos ou dados de pagamento.',supportSend:'Enviar mensagem',supportPrivacy:'Usaremos seu e-mail somente para responder ao atendimento.',supportSent:'Mensagem enviada. O atendimento responderá no e-mail informado.'},
    en: {supportFormKicker:'BOLTMIND SUPPORT',supportFormTitle:'Send your question or suggestion',supportFormLead:'Complete the form below. Your message will be sent directly to support.',supportName:'Your name',supportEmail:'Your email',supportTopic:'Subject',supportTopicQuestion:'Question',supportTopicSuggestion:'Suggestion',supportTopicPurchase:'Purchase',supportMessage:'Question or suggestion',supportPlaceholder:'Write your message. Do not send passwords, codes, or payment details.',supportSend:'Send message',supportPrivacy:'We will use your email only to reply to your request.',supportSent:'Message sent. Support will reply to the email you provided.'},
    pl: {supportFormKicker:'POMOC BOLTMIND',supportFormTitle:'Wyślij pytanie lub sugestię',supportFormLead:'Wypełnij formularz. Wiadomość zostanie przesłana bezpośrednio do pomocy.',supportName:'Twoje imię',supportEmail:'Twój e-mail',supportTopic:'Temat',supportTopicQuestion:'Pytanie',supportTopicSuggestion:'Sugestia',supportTopicPurchase:'Zakup',supportMessage:'Pytanie lub sugestia',supportPlaceholder:'Napisz wiadomość. Nie wysyłaj haseł, kodów ani danych płatniczych.',supportSend:'Wyślij wiadomość',supportPrivacy:'Użyjemy Twojego adresu e-mail wyłącznie do odpowiedzi.',supportSent:'Wiadomość została wysłana. Pomoc odpowie na podany adres e-mail.'},
    el: {supportFormKicker:'ΥΠΟΣΤΗΡΙΞΗ BOLTMIND',supportFormTitle:'Στείλτε την ερώτηση ή την πρότασή σας',supportFormLead:'Συμπληρώστε τη φόρμα. Το μήνυμά σας θα σταλεί απευθείας στην υποστήριξη.',supportName:'Το όνομά σας',supportEmail:'Το email σας',supportTopic:'Θέμα',supportTopicQuestion:'Ερώτηση',supportTopicSuggestion:'Πρόταση',supportTopicPurchase:'Αγορά',supportMessage:'Ερώτηση ή πρόταση',supportPlaceholder:'Γράψτε το μήνυμά σας. Μην στέλνετε κωδικούς ή στοιχεία πληρωμής.',supportSend:'Αποστολή μηνύματος',supportPrivacy:'Το email σας θα χρησιμοποιηθεί μόνο για την απάντησή μας.',supportSent:'Το μήνυμα στάλθηκε. Η υποστήριξη θα απαντήσει στο email που δηλώσατε.'},
    de: {supportFormKicker:'BOLTMIND SUPPORT',supportFormTitle:'Sende deine Frage oder deinen Vorschlag',supportFormLead:'Fülle das Formular aus. Deine Nachricht wird direkt an den Support gesendet.',supportName:'Dein Name',supportEmail:'Deine E-Mail',supportTopic:'Betreff',supportTopicQuestion:'Frage',supportTopicSuggestion:'Vorschlag',supportTopicPurchase:'Kauf',supportMessage:'Frage oder Vorschlag',supportPlaceholder:'Schreibe deine Nachricht. Sende keine Passwörter, Codes oder Zahlungsdaten.',supportSend:'Nachricht senden',supportPrivacy:'Wir verwenden deine E-Mail nur, um auf deine Anfrage zu antworten.',supportSent:'Nachricht gesendet. Der Support antwortet an die angegebene E-Mail-Adresse.'},
    fr: {supportFormKicker:'ASSISTANCE BOLTMIND',supportFormTitle:'Envoyez votre question ou suggestion',supportFormLead:'Remplissez le formulaire. Votre message sera envoyé directement à l’assistance.',supportName:'Votre nom',supportEmail:'Votre e-mail',supportTopic:'Sujet',supportTopicQuestion:'Question',supportTopicSuggestion:'Suggestion',supportTopicPurchase:'Achat',supportMessage:'Question ou suggestion',supportPlaceholder:'Écrivez votre message. N’envoyez aucun mot de passe, code ou donnée de paiement.',supportSend:'Envoyer le message',supportPrivacy:'Votre e-mail servira uniquement à répondre à votre demande.',supportSent:'Message envoyé. L’assistance répondra à l’adresse e-mail indiquée.'}
  };
  Object.entries(supportCopy).forEach(([language, values]) => Object.assign(window.BOLTMIND_I18N[language], values));
  const dialog = document.querySelector('#support-dialog');
  document.querySelectorAll('[data-open-support]').forEach(button => button.addEventListener('click', () => dialog.showModal()));
  const url = new URL(window.location.href);
  if (url.searchParams.get('support') === 'sent') {
    document.querySelector('#support-status').hidden = false;
    dialog.showModal();
    url.searchParams.delete('support');
    history.replaceState({}, '', url.pathname + url.search + '#suporte');
  }
})();
